# Generated by Django 2.2.3 on 2019-08-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190704_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='date',
            field=models.DateTimeField(blank=True, help_text="Select one of 'Yesterday', 'Today', 'Tomorrow'", null=True),
        ),
    ]
