# Generated by Django 3.1.2 on 2020-10-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_city_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='mayor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
